import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {io} from 'socket.io-client';
import './style.css';

// Use the same LAN hostname as the web page. This fixes phone -> laptop signaling.
const SERVER=`${window.location.protocol}//${window.location.hostname}:3001`;
const ICE={iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]};

function Home({onJoin}){
 const [name,setName]=useState(''); const [code,setCode]=useState(''); const [error,setError]=useState('');
 const create=()=>onJoin(name||'Guest',Math.random().toString(36).slice(2,8).toUpperCase());
 const join=()=>{if(!code.trim()){setError('Enter a meeting ID to join.');return}onJoin(name||'Guest',code.trim().toUpperCase())};
 return <div className="home"><div className="homeGlow one"/><div className="homeGlow two"/><div className="homeCard">
  <div className="logo">Gap <span>Shap</span></div><div className="eyebrow">VIDEO COLLABORATION</div><h1>Meet, talk & <em>create</em> together.</h1><p className="lead">Real-time video, audio, chat and screen sharing in one focused workspace.</p>
  <div className="identity"><label>Your name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Enter your name" autoComplete="name"/></label><label>Meeting ID<input value={code} onChange={e=>setCode(e.target.value)} placeholder="6-character code" onKeyDown={e=>e.key==='Enter'&&join()}/></label></div>
  {error&&<div className="error">{error}</div>}
  <div className="homeActions"><button className="primary" onClick={create}>＋ Create meeting</button><button className="secondary" onClick={join}>Join meeting <span>→</span></button></div>
  <div className="homeFeatures"><span>● HD video</span><span>● Live chat</span><span>● Screen share</span><span>● Mobile ready</span></div>
 </div></div>
}
function App(){const [meeting,setMeeting]=useState(null);return meeting?<Meeting {...meeting} onLeave={()=>setMeeting(null)}/>:<Home onJoin={(name,roomId)=>setMeeting({name,roomId})}/>}

function Meeting({name,roomId,onLeave}){
 const socketRef=useRef(null), peers=useRef(new Map()), streamRef=useRef(null), localVideoRef=useRef(null), recorderRef=useRef(null), chunks=useRef([]), reconnecting=useRef(false);
 const [participants,setParticipants]=useState([]),[videos,setVideos]=useState({}),[chat,setChat]=useState([]),[msg,setMsg]=useState(''),[panel,setPanel]=useState('participants'),[mic,setMic]=useState(true),[cam,setCam]=useState(true),[hand,setHand]=useState(false),[sharing,setSharing]=useState(false),[recording,setRecording]=useState(false),[settings,setSettings]=useState(false),[toast,setToast]=useState(''),[reaction,setReaction]=useState(null),[elapsed,setElapsed]=useState(0),[mediaError,setMediaError]=useState('');
 const notify=t=>{setToast(t);window.clearTimeout(notify.timer);notify.timer=window.setTimeout(()=>setToast(''),2400)};
 useEffect(()=>{const t=setInterval(()=>setElapsed(v=>v+1),1000);return()=>clearInterval(t)},[]);
 useEffect(()=>{
  let disposed=false;
  const socket=io(SERVER,{transports:['websocket','polling']});socketRef.current=socket;
  socket.on('connect',()=>{socket.emit('join-room',{roomId,name})});
  socket.on('connect_error',()=>notify(`Cannot reach meeting server at ${SERVER}`));
  const startMedia=async()=>{
   if(!navigator.mediaDevices?.getUserMedia){setMediaError('Camera and microphone require HTTPS on phones. Open Gap Shap using an HTTPS address.');return}
   try{const stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},facingMode:'user'},audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});if(disposed){stream.getTracks().forEach(t=>t.stop());return}streamRef.current=stream;setMediaError('');attachLocal(stream);}
   catch(e){setMediaError(e?.name==='NotAllowedError'?'Camera/microphone permission was denied. Allow both in the browser site settings and rejoin.':`Camera/microphone unavailable (${e?.name||'unknown'}).`)}
  };
  startMedia();
  socket.on('room-users',users=>{setParticipants([{id:socket.id,name,hand:false},...users]);users.forEach(u=>makeOffer(u.id));});
  socket.on('participants',users=>setParticipants(users));
  socket.on('user-joined',u=>notify(`${u.name} joined the meeting`));
  socket.on('user-left',id=>{peers.current.get(id)?.close();peers.current.delete(id);setVideos(v=>{const x={...v};delete x[id];return x});});
  socket.on('signal',async({from,data})=>{try{let pc=peers.current.get(from);if(!pc)pc=createPeer(from,false);if(data.description){await pc.setRemoteDescription(data.description);if(data.description.type==='offer'){const answer=await pc.createAnswer();await pc.setLocalDescription(answer);socket.emit('signal',{to:from,data:{description:pc.localDescription}})}}if(data.candidate){try{await pc.addIceCandidate(data.candidate)}catch{}}}catch{notify('Could not establish a peer connection')}});
  socket.on('chat-message',m=>setChat(c=>[...c,m]));socket.on('reaction',r=>{setReaction(r);setTimeout(()=>setReaction(null),1600)});socket.on('hand',h=>setParticipants(p=>p.map(x=>x.id===h.id?{...x,hand:h.active}:x)));
  return()=>{disposed=true;socket.disconnect();streamRef.current?.getTracks().forEach(t=>t.stop());peers.current.forEach(p=>p.close());window.clearTimeout(notify.timer)};
 },[]);
 function attachLocal(stream){if(localVideoRef.current){localVideoRef.current.srcObject=stream;localVideoRef.current.muted=true;localVideoRef.current.play().catch(()=>{})}}
 function addTracks(pc){streamRef.current?.getTracks().forEach(t=>{if(!pc.getSenders().some(s=>s.track?.kind===t.kind))pc.addTrack(t,streamRef.current)})}
 function createPeer(id,offer=true){const pc=new RTCPeerConnection(ICE);peers.current.set(id,pc);addTracks(pc);pc.onicecandidate=e=>e.candidate&&socketRef.current?.emit('signal',{to:id,data:{candidate:e.candidate}});pc.ontrack=e=>{const s=e.streams[0];if(s)setVideos(v=>({...v,[id]:s}))};pc.onconnectionstatechange=()=>{if(['failed','closed'].includes(pc.connectionState)){peers.current.delete(id)}};if(offer)pc.createOffer().then(o=>pc.setLocalDescription(o)).then(()=>socketRef.current?.emit('signal',{to:id,data:{description:pc.localDescription}}));return pc}
 function makeOffer(id){if(id!==socketRef.current?.id&&!peers.current.has(id))createPeer(id,true)}
 function toggleMic(){const next=!mic;streamRef.current?.getAudioTracks().forEach(t=>t.enabled=next);setMic(next)}
 function toggleCam(){const next=!cam;streamRef.current?.getVideoTracks().forEach(t=>t.enabled=next);setCam(next);if(next&&streamRef.current)attachLocal(streamRef.current)}
 async function share(){if(sharing)return;try{if(!navigator.mediaDevices?.getDisplayMedia){notify('Screen sharing is not supported on this device/browser');return}const s=await navigator.mediaDevices.getDisplayMedia({video:{cursor:'always'},audio:false});const track=s.getVideoTracks()[0];const cameraTrack=streamRef.current?.getVideoTracks()[0];peers.current.forEach(pc=>{const sender=pc.getSenders().find(x=>x.track?.kind==='video');if(sender)sender.replaceTrack(track)});if(localVideoRef.current){localVideoRef.current.srcObject=new MediaStream([track]);localVideoRef.current.play().catch(()=>{})}setSharing(true);notify('You are sharing your screen');track.onended=()=>stopShare(cameraTrack)}catch(e){if(e?.name!=='NotAllowedError')notify('Screen sharing could not start')}}
 function stopShare(cameraTrack){const camera=cameraTrack||streamRef.current?.getVideoTracks()[0];peers.current.forEach(pc=>{const sender=pc.getSenders().find(x=>x.track?.kind==='video');if(sender&&camera)sender.replaceTrack(camera)});if(localVideoRef.current&&streamRef.current)attachLocal(streamRef.current);setSharing(false);notify('Screen sharing stopped')}
 function send(){if(!msg.trim()||!socketRef.current)return;socketRef.current.emit('chat-message',{text:msg});setMsg('')}
 function react(emoji){socketRef.current?.emit('reaction',{emoji});setReaction({name,emoji});setTimeout(()=>setReaction(null),1300)}
 function raise(){const active=!hand;setHand(active);socketRef.current?.emit('hand',{active})}
 function record(){if(recording){recorderRef.current?.stop();setRecording(false);return}const source=streamRef.current;if(!source){notify('Camera stream is not ready');return}const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9,opus')?'video/webm;codecs=vp9,opus':'video/webm';chunks.current=[];const r=new MediaRecorder(source,{mimeType:mime});r.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);r.onstop=()=>{const blob=new Blob(chunks.current,{type:'video/webm'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`gap-shap-${roomId}.webm`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};r.start(500);recorderRef.current=r;setRecording(true)}
 const mins=String(Math.floor(elapsed/60)).padStart(2,'0'),secs=String(elapsed%60).padStart(2,'0');const me=participants.find(p=>p.id===socketRef.current?.id)||{id:'local',name,hand};const others=participants.filter(p=>p.id!==socketRef.current?.id);const all=[{id:'local',name,local:true,hand},...others];
 return <div className="meetingApp"><header className="meetingTop"><div className="logo small">Gap <span>Shap</span></div><div className="meetingTitle"><strong>Team meeting</strong><span>Meeting ID · {roomId}</span><button onClick={()=>navigator.clipboard?.writeText(roomId).then(()=>notify('Meeting ID copied')).catch(()=>notify(`Meeting ID: ${roomId}`))}>⧉</button></div><div className="topRight"><span className="liveDot">●</span>{mins}:{secs}<button className="gear" onClick={()=>setSettings(true)}>⚙</button></div></header>
 <div className="workspace"><aside className="rail"><button className="railLogo">GS</button><button>⌂</button><button className={panel==='participants'?'selected':''} onClick={()=>setPanel('participants')}>♙</button><button className={panel==='chat'?'selected':''} onClick={()=>setPanel('chat')}>◉</button><button onClick={()=>notify('More meeting tools are coming soon')}>•••</button><div className="railBottom"><button onClick={()=>setSettings(true)}>⚙</button><button onClick={onLeave}>↪</button></div></aside>
 <main className="stage"><div className="stageHeader"><div><b>Team meeting</b><small>{participants.length} participant{participants.length!==1?'s':''}</small></div>{sharing&&<span className="sharePill">● Screen sharing</span>}</div>{mediaError&&<div className="mediaWarning">⚠ {mediaError}</div>}<div className={`videoGrid count${Math.min(all.length,6)}`}>{all.map(p=><VideoTile key={p.id} person={p} stream={p.local?streamRef.current:videos[p.id]} cam={p.local?cam:true} mic={p.local?mic:true}/>)}</div>{reaction&&<div className="floatingReaction"><div>{reaction.emoji}</div><small>{reaction.name}</small></div>}
 <div className="bottomBar"><Control icon={mic?'🎙':'🔇'} label={mic?'Mute':'Unmute'} onClick={toggleMic} off={!mic}/><Control icon={cam?'▣':'▧'} label={cam?'Stop video':'Start video'} onClick={toggleCam} off={!cam}/><Control icon={sharing?'▣':'⌘'} label={sharing?'Sharing':'Share'} onClick={sharing?()=>stopShare():share} active={sharing}/><Control icon="♙" label="People" onClick={()=>setPanel('participants')} active={panel==='participants'}/><Control icon="◌" label="Chat" onClick={()=>setPanel('chat')} active={panel==='chat'}/><Control icon="✋" label="Hand" onClick={raise} active={hand}/><Control icon="☺" label="React" onClick={()=>react('👍')}/><Control icon="●" label={recording?'Stop':'Record'} onClick={record} active={recording}/><button className="leaveBtn" onClick={onLeave}>☎ <span>Leave</span></button></div></main>
 {panel&&<aside className="sidePanel"><div className="panelTabs"><button className={panel==='participants'?'active':''} onClick={()=>setPanel('participants')}>People <b>{participants.length}</b></button><button className={panel==='chat'?'active':''} onClick={()=>setPanel('chat')}>Chat</button><button className="closePanel" onClick={()=>setPanel(null)}>×</button></div>{panel==='participants'?<div className="participantList">{participants.map(p=><div className="participant" key={p.id}><div className="avatar">{p.name[0]?.toUpperCase()}</div><div><strong>{p.name}{p.id===socketRef.current?.id?' (You)':''}</strong><small>{p.hand?'✋ Raised hand':'In meeting'}</small></div><span>{p.id===socketRef.current?.id?(mic?'🎙':'🔇'):'🎙'}</span></div>)}</div>:<><div className="chatList">{chat.length===0?<div className="emptyChat"><div>💬</div><strong>Start the conversation</strong><p>Messages from everyone in this meeting appear here.</p></div>:chat.map((m,i)=><div className={`chatMsg ${m.id===socketRef.current?.id?'mine':''}`} key={i}><div className="chatMeta"><b>{m.name}</b><span>{new Date(m.time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span></div><div className="bubble">{m.text}</div></div>)}</div><div className="composer"><input value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Type a message…"/><button onClick={send}>➤</button></div></>}</aside>}</div>
 {settings&&<div className="modal"><div className="modalCard"><button className="close" onClick={()=>setSettings(false)}>×</button><div className="modalIcon">⚙</div><h2>Meeting settings</h2><p>Camera and audio are controlled by your browser. On a phone, use an HTTPS URL for camera/mic access.</p><div className="settingInfo"><span>Server</span><b>{SERVER}</b></div><div className="settingInfo"><span>Meeting</span><b>{roomId}</b></div><button className="primary full" onClick={()=>setSettings(false)}>Done</button></div></div>}{toast&&<div className="toast">{toast}</div>}</div>
}
function Control({icon,label,onClick,active,off}){return <button className={`control ${active?'active':''} ${off?'off':''}`} onClick={onClick}><span>{icon}</span><small>{label}</small></button>}
function VideoTile({person,stream,cam,mic}){const ref=useRef(null);useEffect(()=>{if(ref.current&&stream){ref.current.srcObject=stream;ref.current.play().catch(()=>{})}},[stream]);return <div className={`tile ${person.local?'localTile':''}`}>{stream&&cam?<video ref={ref} autoPlay playsInline muted={person.local}/>:<div className="tileAvatar">{person.name[0]?.toUpperCase()}</div>}<div className="tileName"><span>{person.name}{person.local?' (You)':''}</span>{!mic&&<b>🔇</b>}{person.hand&&<b>✋</b>}</div>{person.local&&<div className="youBadge">YOU</div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
